# Generated by Django 2.2.14 on 2020-08-10 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The 'course' part of course_keys associated with this course code, for example 'DemoX' in 'edX/DemoX/Demo_Course'.", max_length=128)),
                ('display_name', models.CharField(help_text='The display name of this course code.', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='The user-facing display name for this Program.', max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='A brief, descriptive subtitle for the Program.', max_length=255)),
                ('marketing_slug', models.CharField(blank=True, help_text='Slug used to generate links to the marketing site', max_length=255)),
                ('length_of_program', models.CharField(blank=True, max_length=25, null=True)),
                ('effort', models.CharField(blank=True, max_length=25, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('program_code', models.CharField(blank=True, max_length=50, null=True)),
                ('program_code_friendly_name', models.CharField(blank=True, max_length=50, null=True)),
                ('enrolled_students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('position', models.IntegerField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci_program.CourseCode')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci_program.Program')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='coursecode',
            name='programs',
            field=models.ManyToManyField(related_name='course_codes', through='ci_program.ProgramCourseCode', to='ci_program.Program'),
        ),
    ]
