# Generated by Django 2.2.14 on 2020-09-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
    ]
