# Generated by Django 2.2.14 on 2022-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0002_auto_20200923_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='specialization_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
