# Generated by Django 2.2.14 on 2022-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0003_program_specialization_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sample_content_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='support_program_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='support_program_sources',
            field=models.TextField(blank=True, help_text='Comma-separated list of student sources (colleges) eligible for the support Program', null=True),
        ),
    ]
