# Generated by Django 2.2.14 on 2022-12-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0005_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='The user-facing display name for this Program.', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
