# Generated by Django 2.2.14 on 2022-12-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0005_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='support_program_for',
            field=models.TextField(blank=True, help_text='Comma-separated list of main Program codes eligible for the support Program', null=True),
        ),
    ]
