# Generated by Django 2.2.14 on 2022-12-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0005_program_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='sample_content_for',
            new_name='sample_content',
        ),
        migrations.RemoveField(
            model_name='program',
            name='support_program_for',
        ),
        migrations.AddField(
            model_name='program',
            name='support_programs',
            field=models.TextField(blank=True, help_text='Comma-separated list of support programmes to enrol together with main programme', null=True),
        ),
    ]
