# Generated by Django 2.2.14 on 2023-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0005_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sample_content',
            field=models.ManyToManyField(related_name='sampled_main_programs', to='ci_program.Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='support_programs',
            field=models.ManyToManyField(related_name='supported_main_programs', to='ci_program.Program'),
        ),
    ]
