# Generated by Django 2.2.14 on 2023-06-13 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ci_program', '0006_auto_20221219_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
