# Generated by Django 2.2.14 on 2020-08-10 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sort_key', models.IntegerField()),
            ],
            options={
                'ordering': ('sort_key',),
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('block_locator', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('Required', 'Required'), ('Bonus', 'Bonus'), ('Optional', 'Optional')], max_length=50)),
                ('tags', models.ManyToManyField(to='challenges.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_challenge_started', models.DateTimeField()),
                ('time_challenge_submitted', models.DateTimeField()),
                ('passed', models.BooleanField()),
                ('attempts', models.IntegerField(default=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'challenge')},
            },
        ),
    ]
