# Generated by Django 2.2.12 on 2020-05-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0001_squashed_0026_auto_20200401_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltiproviderconfig',
            name='visible',
        ),
    ]
